# Generated by Django 2.1.1 on 2018-10-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toUser', models.EmailField(max_length=254)),
                ('fromUser', models.EmailField(max_length=254)),
                ('subjectEmail', models.CharField(max_length=264)),
                ('bodyEmail', models.CharField(max_length=264)),
            ],
        ),
    ]
